apiVersion: v1
kind: ConfigMap
metadata:
  name: pfe-ai-config
  namespace: pfe
data:
  PORT: "6000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-ai-service
  namespace: pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-ai-service
  template:
    metadata:
      labels:
        app: pfe-ai-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ai-service
          image: ghcr.io/kannou1/pfe-ai-service:latest
          ports:
            - containerPort: 6000
          envFrom:
            - configMapRef:
                name: pfe-ai-config
---
apiVersion: v1
kind: Service
metadata:
  name: pfe-ai-service
  namespace: pfe
spec:
  selector:
    app: pfe-ai-service
  ports:
    - port: 6000
      targetPort: 6000
  type: ClusterIP
