apiVersion: v1
kind: ConfigMap
metadata:
  name: pfe-backend-config
  namespace: pfe
data:
  PORT: "5000"
  AI_SERVICE_URL: "http://pfe-ai-service:7000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-backend
  namespace: pfe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pfe-backend
  template:
    metadata:
      labels:
        app: pfe-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/kannou1/pfe-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: pfe-backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: pfe-backend
  namespace: pfe
spec:
  selector:
    app: pfe-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
