apiVersion: v1
kind: ConfigMap
metadata:
  name: pfe-frontend-config
  namespace: pfe
data:
  REACT_APP_API_URL: "http://pfe-backend:5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-frontend
  namespace: pfe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pfe-frontend
  template:
    metadata:
      labels:
        app: pfe-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/kannou1/pfe-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pfe-frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: pfe-frontend
  namespace: pfe
spec:
  selector:
    app: pfe-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
